import { Navbar } from "@/components/site/Navbar";
import { Footer } from "@/components/site/Footer";

export default function TermsPage() {
  return (
    <main className="bg-background min-h-screen text-ink">
      <Navbar />
      <div className="pt-32 pb-20 shell max-w-4xl mx-auto px-6">
        <h1 className="display text-4xl sm:text-5xl font-bold mb-8 text-purple tracking-tight">Terms and Conditions</h1>
        
        <div className="space-y-8 text-base text-muted-foreground leading-relaxed">
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-ink">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Koshin AI ("the Service"), you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you may not use our Service. The Service is provided by Koshin Inc., and your use constitutes a legally binding agreement.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-ink">2. Description of Service</h2>
            <p>
              Koshin AI is a financial health dashboard and expense analyzer. We provide automated categorization, subscription tracking, budget simulation, and AI-driven financial insights. We do not provide professional financial, legal, or tax advice. All insights generated by the AI Advisor are for informational purposes only.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-ink">3. User Accounts & Security</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>You must be at least 18 years old to use the Service.</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials (including OTP verification codes).</li>
              <li>You must immediately notify us of any unauthorized use of your account.</li>
              <li>We reserve the right to suspend or terminate accounts that violate these terms.</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-ink">4. Data Privacy & Financial Information</h2>
            <p>
              Koshin AI takes your privacy seriously. Your bank statements, manual transaction entries, and AI receipt scans are encrypted and processed securely. We do not sell your personal financial data to third parties. For complete details on how we handle your data, please refer to our Privacy Policy.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-ink">5. Limitations of Liability</h2>
            <p>
              Koshin AI is provided on an "as is" and "as available" basis. We make no warranties, expressed or implied, regarding the accuracy, reliability, or availability of the Service. In no event shall Koshin Inc. be liable for any direct, indirect, incidental, or consequential damages resulting from your use of the Service or reliance on the AI Advisor's insights.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-ink">6. Modifications to the Service</h2>
            <p>
              We reserve the right to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. We shall not be liable to you or any third party for any modification, suspension, or discontinuance of the Service.
            </p>
          </section>

          <p className="text-sm pt-8 border-t border-hairline mt-12">
            Last updated: August 2026. For questions regarding these terms, contact legal@koshin.ai.
          </p>
        </div>
      </div>
      <Footer />
    </main>
  );
}
